version: "3.9"

services:
  admin:
    build: ./admin
    container_name: admin
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./admin:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True

  # main:
  #   build: ./main
  #   container_name: main
  #   restart: always
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - ./main:/app
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - SECRET_KEY=test
  #     - DEBUG=True
  
